# Dictionary to map the names of the points to their respective values
POINTS_ORIGINAL = {
    "NOSE": 0,
    "LEFT_EYE_INNER": 1,
    "LEFT_EYE": 2,
    "LEFT_EYE_OUTER": 3,
    "RIGHT_EYE_INNER": 4,
    "RIGHT_EYE": 5,
    "RIGHT_EYE_OUTER": 6,
    "LEFT_EAR": 7,
    "RIGHT_EAR": 8,
    "MOUTH_LEFT": 9,
    "MOUTH_RIGHT": 10,
    "LEFT_SHOULDER": 11,
    "RIGHT_SHOULDER": 12,
    "LEFT_ELBOW": 13,
    "RIGHT_ELBOW": 14,
    "LEFT_WRIST": 15,
    "RIGHT_WRIST": 16,
    "LEFT_PINKY": 17,
    "RIGHT_PINKY": 18,
    "LEFT_INDEX": 19,
    "RIGHT_INDEX": 20,
    "LEFT_THUMB": 21,
    "RIGHT_THUMB": 22,
    "LEFT_HIP": 23,
    "RIGHT_HIP": 24,
    "LEFT_KNEE": 25,
    "RIGHT_KNEE": 26,
    "LEFT_ANKLE": 27,
    "RIGHT_ANKLE": 28,
    "LEFT_HEEL": 29,
    "RIGHT_HEEL": 30,
    "LEFT_FOOT_INDEX": 31,
    "RIGHT_FOOT_INDEX": 32
}

# Dictionary to map the names of the points to their respective values with "LEFT" replaced by "RIGHT" and vice versa
POINTS_FLIPPED = {
    "NOSE": 0,
    "RIGHT_EYE_INNER": 1,
    "RIGHT_EYE": 2,
    "RIGHT_EYE_OUTER": 3,
    "LEFT_EYE_INNER": 4,
    "LEFT_EYE": 5,
    "LEFT_EYE_OUTER": 6,
    "RIGHT_EAR": 7,
    "LEFT_EAR": 8,
    "MOUTH_RIGHT": 9,
    "MOUTH_LEFT": 10,
    "RIGHT_SHOULDER": 11,
    "LEFT_SHOULDER": 12,
    "RIGHT_ELBOW": 13,
    "LEFT_ELBOW": 14,
    "RIGHT_WRIST": 15,
    "LEFT_WRIST": 16,
    "RIGHT_PINKY": 17,
    "LEFT_PINKY": 18,
    "RIGHT_INDEX": 19,
    "LEFT_INDEX": 20,
    "RIGHT_THUMB": 21,
    "LEFT_THUMB": 22,
    "RIGHT_HIP": 23,
    "LEFT_HIP": 24,
    "RIGHT_KNEE": 25,
    "LEFT_KNEE": 26,
    "RIGHT_ANKLE": 27,
    "LEFT_ANKLE": 28,
    "RIGHT_HEEL": 29,
    "LEFT_HEEL": 30,
    "RIGHT_FOOT_INDEX": 31,
    "LEFT_FOOT_INDEX": 32
}


JOINTS_ORIGINAL = {
    "LEFT_SHOULDER": [POINTS_ORIGINAL["LEFT_ELBOW"], POINTS_ORIGINAL["LEFT_SHOULDER"], POINTS_ORIGINAL["LEFT_HIP"]],
    "RIGHT_SHOULDER": [POINTS_ORIGINAL["RIGHT_ELBOW"], POINTS_ORIGINAL["RIGHT_SHOULDER"], POINTS_ORIGINAL["RIGHT_HIP"]],
    "LEFT_ELBOW": [POINTS_ORIGINAL["LEFT_SHOULDER"], POINTS_ORIGINAL["LEFT_ELBOW"], POINTS_ORIGINAL["LEFT_WRIST"]],
    "RIGHT_ELBOW": [POINTS_ORIGINAL["RIGHT_SHOULDER"], POINTS_ORIGINAL["RIGHT_ELBOW"], POINTS_ORIGINAL["RIGHT_WRIST"]],
    "LEFT_HIP": [POINTS_ORIGINAL["LEFT_SHOULDER"], POINTS_ORIGINAL["LEFT_HIP"], POINTS_ORIGINAL["LEFT_KNEE"]],
    "RIGHT_HIP": [POINTS_ORIGINAL["RIGHT_SHOULDER"], POINTS_ORIGINAL["RIGHT_HIP"], POINTS_ORIGINAL["RIGHT_KNEE"]],
    "LEFT_KNEE": [POINTS_ORIGINAL["LEFT_HIP"], POINTS_ORIGINAL["LEFT_KNEE"], POINTS_ORIGINAL["LEFT_ANKLE"]],
    "RIGHT_KNEE": [POINTS_ORIGINAL["RIGHT_HIP"], POINTS_ORIGINAL["RIGHT_KNEE"], POINTS_ORIGINAL["RIGHT_ANKLE"]],
    "LEFT_ANKLE": [POINTS_ORIGINAL["LEFT_KNEE"], POINTS_ORIGINAL["LEFT_ANKLE"], POINTS_ORIGINAL["LEFT_FOOT_INDEX"]],
    "RIGHT_ANKLE": [POINTS_ORIGINAL["RIGHT_KNEE"], POINTS_ORIGINAL["RIGHT_ANKLE"], POINTS_ORIGINAL["RIGHT_FOOT_INDEX"]],
    # "NECK": [POINTS_ORIGINAL["LEFT_EAR"], POINTS_ORIGINAL["NOSE"], POINTS_ORIGINAL["RIGHT_EAR"], POINTS_ORIGINAL["LEFT_SHOULDER"], POINTS_ORIGINAL["RIGHT_SHOULDER"]]
    
    # ... add other joints as needed
}

JOINTS_FLIPPED = {
    "LEFT_SHOULDER": [POINTS_FLIPPED["LEFT_ELBOW"], POINTS_FLIPPED["LEFT_SHOULDER"], POINTS_FLIPPED["LEFT_HIP"]],
    "RIGHT_SHOULDER": [POINTS_FLIPPED["RIGHT_ELBOW"], POINTS_FLIPPED["RIGHT_SHOULDER"], POINTS_FLIPPED["RIGHT_HIP"]],
    "LEFT_ELBOW": [POINTS_FLIPPED["LEFT_SHOULDER"], POINTS_FLIPPED["LEFT_ELBOW"], POINTS_FLIPPED["LEFT_WRIST"]],
    "RIGHT_ELBOW": [POINTS_FLIPPED["RIGHT_SHOULDER"], POINTS_FLIPPED["RIGHT_ELBOW"], POINTS_FLIPPED["RIGHT_WRIST"]],
    "LEFT_HIP": [POINTS_FLIPPED["LEFT_SHOULDER"], POINTS_FLIPPED["LEFT_HIP"], POINTS_FLIPPED["LEFT_KNEE"]],
    "RIGHT_HIP": [POINTS_FLIPPED["RIGHT_SHOULDER"], POINTS_FLIPPED["RIGHT_HIP"], POINTS_FLIPPED["RIGHT_KNEE"]],
    "LEFT_KNEE": [POINTS_FLIPPED["LEFT_HIP"], POINTS_FLIPPED["LEFT_KNEE"], POINTS_FLIPPED["LEFT_ANKLE"]],
    "RIGHT_KNEE": [POINTS_FLIPPED["RIGHT_HIP"], POINTS_FLIPPED["RIGHT_KNEE"], POINTS_FLIPPED["RIGHT_ANKLE"]],
    "LEFT_ANKLE": [POINTS_FLIPPED["LEFT_KNEE"], POINTS_FLIPPED["LEFT_ANKLE"], POINTS_FLIPPED["LEFT_FOOT_INDEX"]],
    "RIGHT_ANKLE": [POINTS_FLIPPED["RIGHT_KNEE"], POINTS_FLIPPED["RIGHT_ANKLE"], POINTS_FLIPPED["RIGHT_FOOT_INDEX"]],
    # "NECK":[POINTS_FLIPPED["LEFT_EAR"], POINTS_FLIPPED["NOSE"], POINTS_FLIPPED["RIGHT_EAR"], POINTS_FLIPPED["LEFT_SHOULDER"], POINTS_FLIPPED["RIGHT_SHOULDER"]]
    
    # ... add other joints as needed
}


DISTANCES_ORIGINAL = {
    "KNEE_DISTANCE": [POINTS_ORIGINAL["LEFT_KNEE"], POINTS_ORIGINAL["RIGHT_KNEE"]],
    "ANKLE_DISTANCE": [POINTS_ORIGINAL["LEFT_ANKLE"], POINTS_ORIGINAL["RIGHT_ANKLE"]],
    "ELBOW_DISTANCE": [POINTS_ORIGINAL["LEFT_ELBOW"], POINTS_ORIGINAL["RIGHT_ELBOW"]],
    "WRIST_DISTANCE": [POINTS_ORIGINAL["LEFT_WRIST"], POINTS_ORIGINAL["RIGHT_WRIST"]]
}


DISTANCES_FLIPPED = {
    "KNEE_DISTANCE": [POINTS_FLIPPED["LEFT_KNEE"], POINTS_FLIPPED["RIGHT_KNEE"]],
    "ANKLE_DISTANCE": [POINTS_FLIPPED["LEFT_ANKLE"], POINTS_FLIPPED["RIGHT_ANKLE"]],
    "ELBOW_DISTANCE": [POINTS_FLIPPED["LEFT_ELBOW"], POINTS_FLIPPED["RIGHT_ELBOW"]],
    "WRIST_DISTANCE": [POINTS_FLIPPED["LEFT_WRIST"], POINTS_FLIPPED["RIGHT_WRIST"]]
}




COLORS_BGR = {
    "BLUE": (255, 0, 0),
    "GREEN": (0, 255, 0),
    "RED": (0, 0, 255),
    "YELLOW": (0, 255, 255),
    "MAGENTA": (255, 0, 255),
    "CYAN": (255, 255, 0),
    "WHITE": (255, 255, 255),
    "BLACK": (0, 0, 0),
    "GRAY": (128, 128, 128),
    "ORANGE": (0, 165, 255),
    "PURPLE": (128, 0, 128),
    "PINK": (203, 192, 255),
    "BROWN": (0, 42, 165),
    "GOLD": (0, 215, 255),
    "NAVY": (128, 0, 0),
    "LIME": (0, 255, 50),
    "TEAL": (128, 128, 0),
    "MAROON": (0, 0, 128),
    "OLIVE": (0, 128, 128),
    "BEIGE": (220, 245, 245),
    "INDIGO": (130, 0, 75),
    "VIOLET": (221, 0, 255),
    "SILVER": (192, 192, 192),
    "ROSE": (203, 105, 255),
    "PEACH": (185, 218, 255)
}



